import './global.css'
import ResponsiveHeader from "@/components/responsiveHeader/ResponsiveHeader"
import Background from "@/components/background/Background"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          {<ResponsiveHeader/>}
          {<Background/>}
          <div className="absolute top-0 right-0 left-0 bottom-0 z-50 pt-14 h-[100vh] overflow-y-scroll overflow-x-hidden">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
